# Generated by Django 3.1.2 on 2020-10-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='age_qul',
            field=models.CharField(max_length=256, null=True, verbose_name='age_qul'),
        ),
    ]
