# Generated by Django 3.1.2 on 2020-10-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201031_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pub_date',
            field=models.CharField(max_length=256, null=True, verbose_name='pub_date'),
        ),
    ]
