# Generated by Django 3.1.2 on 2020-10-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201031_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='age_qul',
            field=models.CharField(max_length=512, null=True, verbose_name='age_qul'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='author',
            field=models.CharField(max_length=512, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='categories',
            field=models.CharField(max_length=512, null=True, verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='city',
            field=models.CharField(max_length=512, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='lib_cat',
            field=models.CharField(max_length=512, null=True, verbose_name='lib_cat'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=512, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='pub_date',
            field=models.CharField(max_length=512, null=True, verbose_name='pub_date'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='publisher',
            field=models.CharField(max_length=512, null=True, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='series',
            field=models.CharField(max_length=512, null=True, verbose_name='series'),
        ),
    ]
