# Generated by Django 3.1.2 on 2020-10-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201031_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='start_date'),
        ),
    ]
