# Generated by Django 3.1.2 on 2020-10-31 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201031_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
    ]
