# Generated by Django 3.1.2 on 2020-10-31 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_remove_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='end_date',
            field=models.DateField(null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='start_date',
            field=models.DateField(null=True, verbose_name='start_date'),
        ),
    ]
