# Generated by Django 3.1.2 on 2020-10-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201031_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='catalog_id')),
                ('EventName', models.CharField(max_length=256, null=True, verbose_name='event_name')),
                ('PlaceName', models.CharField(max_length=64, null=True, verbose_name='place_name')),
                ('EventType', models.CharField(max_length=128, null=True, verbose_name='event_type')),
                ('Holiday', models.CharField(max_length=256, null=True, verbose_name='holiday')),
                ('DateStart', models.CharField(max_length=64, null=True, verbose_name='date_start')),
                ('TimeStart', models.CharField(max_length=64, null=True, verbose_name='time_start')),
                ('DateEnd', models.CharField(max_length=64, null=True, verbose_name='date_end')),
                ('TimeEnd', models.CharField(max_length=64, null=True, verbose_name='time_end')),
                ('Description', models.CharField(max_length=2048, null=True, verbose_name='description')),
                ('Online', models.CharField(max_length=3, null=True, verbose_name='online')),
                ('Address', models.CharField(max_length=128, null=True, verbose_name='address')),
                ('Region', models.CharField(max_length=128, null=True, verbose_name='region')),
                ('Disabilities', models.CharField(max_length=512, null=True, verbose_name='disabilities')),
                ('AgeFrom', models.IntegerField(verbose_name='age_from')),
                ('AgeTo', models.IntegerField(verbose_name='age_to')),
                ('ODA', models.BooleanField(verbose_name='oda')),
                ('Hearing', models.BooleanField(verbose_name='hearing')),
                ('Vision', models.BooleanField(verbose_name='vision')),
                ('Wheelchair', models.BooleanField(verbose_name='wheelchair')),
            ],
        ),
    ]
