# Generated by Django 3.1.2 on 2020-10-31 23:43

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0008_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('oda', models.IntegerField(null=True, verbose_name='oda')),
                ('hearing', models.IntegerField(null=True, verbose_name='hearing')),
                ('vision', models.IntegerField(null=True, verbose_name='vision')),
                ('wheelchair', models.IntegerField(null=True, verbose_name='wheelchair')),
                ('interes', models.CharField(max_length=1024, null=True, verbose_name='interes')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='reader',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
